Django_Frolov/urls.py
from django.contrib import admin
from django.urls import path

from students import views as student_views
from group import views as group_views
from teachers import views as teacher_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', student_views.home),
    path('generate-student/', student_views.generate_student),
    path('generate-students/', student_views.generate_students),
    path('groups/', group_views.groups),
    path('teachers/', teacher_views.teachers),
]

django_frolov/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path

from .views import error_404, error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('general.urls')),
    path('', include('students.urls')),
    path('', include('groups.urls')),
    path('', include('teachers.urls')),
    path('', include('contact_us.urls')),
    path('', include('currency.urls')),
    path('__debug__/', include(debug_toolbar.urls))
]

handler404 = error_404
handler500 = error_500

groups/urls.py
from django.urls import path

from .views import (
    CreateGroupFormView,
    DeleteGroupView,
    EditGroupFormView,
    GroupsListView,
)


urlpatterns = [
    path('list_groups/', GroupsListView.as_view(), name='list-groups'),
    path('create_group_form/', CreateGroupFormView.as_view(), name='create-groups-form'),
    path('edit_group_form/<int:group_id>', EditGroupFormView.as_view(), name='edit-group-form'),
    path('delete_group/<int:pk>', DeleteGroupView.as_view(), name='delete-group')

]

hillel_django_project/hillel_django_project/urls.py
from django.contrib import admin
from django.urls import path

from students import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('generate-student/', views.generate_student),
    path('generate-students/', views.generate_students),
    path('groups/', views.groups),
    path('teachers/', views.teachers),
]

groups/models.py
from django.db import models

from students.models import Student

from teachers.models import Teacher


class Group(models.Model):
    group_name = models.CharField(max_length=40, unique=False)
    discipline = models.CharField(max_length=40, null=True, blank=True, default='Programming')
    curator = models.ForeignKey(Teacher, null=True, default=None, blank=True, on_delete=models.PROTECT)
    headman = models.ForeignKey(Student, null=True, default=None, blank=True, on_delete=models.CASCADE)
    students = models.ManyToManyField(
        Student,
        related_name="students_in_group",
        default=None,
        blank=True,
        max_length=10
    )

    def students_list(self):
        return ", \n".join([str(s) for s in self.students.all()])

    def __str__(self):
        return self.group_name

groups/forms.py
from django import forms

from .models import Group

"""
class GroupForm(forms.Form):
    group_name = forms.CharField(label='Group name:', required=True, max_length=40)
    discipline = forms.CharField(label='Discipline:', required=True, max_length=40)
    students = forms.ModelMultipleChoiceField(queryset=Student.objects.all())
    curator = forms.ModelChoiceField(queryset=Teacher.objects.all())"""


class GroupFormFormModel(forms.ModelForm):
    def clean_students(self):
        students = self.cleaned_data['students']
        headman = self.cleaned_data['headman']
        if len(students) > 10:
            raise forms.ValidationError('You can add maximum 10 students!')
        elif headman not in students:
            raise forms.ValidationError('The headman must be in the group!')
        return students

    class Meta:
        model = Group
        fields = ['group_name', 'discipline', 'curator', 'headman', 'students']
        widgets = {
            'students': forms.CheckboxSelectMultiple()
        }

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from .forms import GroupFormFormModel
from .models import Group


class GroupsListView(ListView):
    model = Group
    template_name = 'groups/list_groups.html'


class CreateGroupFormView(LoginRequiredMixin, View):
    template_name = 'groups/create_group_form.html'
    form_class = GroupFormFormModel

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            groups = Group.objects.create(
                group_name=form.cleaned_data["group_name"],
                discipline=form.cleaned_data["discipline"],
                curator=form.cleaned_data["curator"],
                headman=form.cleaned_data["headman"],
            )

            for student in form.cleaned_data['students']:
                groups.students.add(student)

            return redirect('list-groups')

        return render(request, self.template_name, {'form': form})


class EditGroupFormView(LoginRequiredMixin, View):
    template_name = 'groups/edit_group_form.html'
    form_class = GroupFormFormModel

    def get(self, request, *args, **kwargs):
        group = Group.objects.filter(id=kwargs['group_id']).first()
        form = GroupFormFormModel(instance=group)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():  # If form valid:
            # To the variable group, assign the filtered group by ID from the database
            group = Group.objects.filter(id=kwargs['group_id']).first()

            group.group_name = form.cleaned_data["group_name"]  # Update object 'group_name' field
            group.discipline = form.cleaned_data["discipline"]  # Update object 'discipline' field
            group.curator = form.cleaned_data["curator"]  # Update object 'curator' field
            group.headman = form.cleaned_data["headman"]  # Update object 'headman' field
            group.save()  # Save all changes in object fields

            group.students.clear()  # clean all the many-to-many relationships of the object field 'students'
            group.save()  # Save all changes in object fields

            # Add new links from the form.list to the object field 'students' one by one
            for student in form.cleaned_data['students']:
                group.students.add(student)

            return redirect('list-groups')

        return render(request, self.template_name, {'form': form})


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    template_name = 'groups/group_confirm_delete.html'
    model = Group
    success_url = reverse_lazy('list-groups')

templates/groups/create_group_form.html
{% extends "base.html" %}
{% block title %}
    Create group form
{% endblock %}
{% block page_title %}Create group form{% endblock %}
{% block content %}
    <form class="container" method="post">
        {% csrf_token %}
        <table class="table table-striped">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Save form">
    </form>
{% endblock %}

templates/groups/edit_group_form.html
{% extends "base.html" %}
{% block title %}
    Edit group form
{% endblock %}
{% block page_title %}Edit group form{% endblock %}
{% block content %}
    <form class="container" method="post">
        {% csrf_token %}
        <table class="table table-striped">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Save form">
    </form>
{% endblock %}

templates/groups/group_confirm_delete.html
{% extends "base.html" %}
    {% block title %}
        Student creation form
    {% endblock %}
    {% block page_title %}Are you sure you want to delete "{{ object }}"?{% endblock %}
    {% block content %}
        <form class="container" method="post" align="center">
            {% csrf_token %}
            <input type="submit" value="Confirm">
        </form>
    {% endblock %}

templates/groups/list_groups.html
{% extends "base.html" %}
    {% block title %}
        List groups
    {% endblock %}
    {% block page_title %}List groups{% endblock %}
    {% block content %}
        <table class="container table table-bordered border-black-50">
            <thead class="table-dark">
                <tr class="active">
                    <th scope="col">id</th>
                    <th scope="col">Group name</th>
                    <th scope="col">Discipline</th>
                    <th scope="col">Curator</th>
                    <th scope="col">Headman</th>
                    <th scope="col">Students in group</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for group in group_list %}
                <tr>
                    <td>{{ group.id|safe  }}</td>
                    <td>{{ group.group_name|safe }}</td>
                    <td>{{ group.discipline|safe }}</td>
                    <td>{{ group.curator|safe }}</td>
                    <td>{{ group.headman|safe }}</td>
                    <td>
                        <ul>
                            {% for student in group.students.all %}
                                <li>{{ student.first_name }} {{ student.last_name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <li><a href="{% url 'edit-group-form' group.id %}">Edit</a></li>
                            <li><a href="{% url 'delete-group' group.id %}">Delete</a></li>
                        </ul>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endblock %}